import { Toaster } from "@/components/ui/sonner";
import { SessionHookProvider } from "@/lib/session";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { AUTH_OPTIONS } from "@/features/auth/config/auth.config";
import { QueryProviders } from "@/components/query-provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kiara Directory",
  description: "Generated by create next app",
  applicationName: "Kiara Directory",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const session = await getServerSession(AUTH_OPTIONS);

  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetBrainsMono.variable} antialiased`}
      >
        <QueryProviders>
          <SessionHookProvider session={session}>
            {children}
            {modal}
          </SessionHookProvider>
        </QueryProviders>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
