import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { SessionHookProvider } from "@/lib/session";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kiara Directory",
  description: "Generated by create next app",
  applicationName: "Kiara Directory",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetBrainsMono.variable} antialiased`}
      >
        <SessionHookProvider session={session}>{children}</SessionHookProvider>
        <Toaster />
      </body>
    </html>
  );
}
