-- AlterTable
ALTER TABLE `companies` MODIFY `updated_at` TIMESTAMP(3) NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `divisions` MODIFY `updated_at` TIMESTAMP(3) NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `projects` MODIFY `updated_at` TIMESTAMP(3) NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `roles` MODIFY `updated_at` TIMESTAMP(3) NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `team_users` MODIFY `updated_at` TIMESTAMP(3) NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `teams` MODIFY `updatedAt` TIMESTAMP(3) NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `user_divisions` MODIFY `updated_at` TIMESTAMP(3) NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `users` MODIFY `updated_at` TIMESTAMP(3) NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(3);
