export const ROLE_QUERY_KEYS = {
  API_GET: "QUERY.API.ROLES",
  API_GET_SCOPE_DIVISION: "QUERY.API.DIVISIONS",
  API_GET_SCOPE_FIELD: "QUERY.API.FIELDS",
  API_GET_SCOPE_DEPARTMENT: "QUERY.API.DEPARTMENTS",
  API_GET_SCOPE: "QUERY.API.SCOPE",
};
